# Starter

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os

root = "../input"

print(os.listdir(root))

# Any results you write to the current directory are saved as output.

['test.csv', 'train.csv', 'sample_submission.csv']

# Check Data

In [2]:
sample_df = pd.read_csv(os.path.join(root, 'sample_submission.csv'))
train_df = pd.read_csv(os.path.join(root, 'train.csv'))
test_df = pd.read_csv(os.path.join(root, 'test.csv'))

In [3]:
sample_df.head()

          ID        target
0  000137c73  5.944923e+06
1  00021489f  5.944923e+06
2  0004d7953  5.944923e+06
3  00056a333  5.944923e+06
4  00056d8eb  5.944923e+06

In [4]:
print("Train:", train_df.shape, "Test:", test_df.shape)

Train: (4459, 4993) Test: (49342, 4992)

# Clean Data
TBD

# Preprocess Data

In [5]:
# Get the target
test_ID = test_df['ID']
y = np.log1p(train_df.target)

train_df.drop(["ID", "target"], axis=1, inplace=True)
test_df.drop(["ID"], axis=1, inplace=True)

train_df.head()

,48df886f9,0deb4b6a8,34b15f335,a8cb14b00,2f0771a37,30347e683,d08d1fbe3,6ee66e115,20aa07010,dc5a8f1d8,...,3ecc09859,9281abeea,8675bec0b,3a13ed79a,f677d4d13,71b203550,137efaa80,fb36b89d9,7e293fbaf,9fc776466
0,0.0,0,0.0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0,0,0,0
1,0.0,0,0.0,0,0,0,0,0,2200000.0,0.0,...,0.0,0.0,0.0,0,0,0,0,0,0,0
2,0.0,0,0.0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0,0,0,0
3,0.0,0,0.0,0,0,0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0,0,0,0,0,0
4,0.0,0,0.0,0,0,0,0,0,2000000.0,0.0,...,0.0,0.0,0.0,0,0,0,0,0,0,0

In [6]:
# logarithmic
train_df.loc[:, :] = np.log1p(train_df.values)
test_df.loc[:, :] = np.log1p(test_df.values)

train_df.head()

,48df886f9,0deb4b6a8,34b15f335,a8cb14b00,2f0771a37,30347e683,d08d1fbe3,6ee66e115,20aa07010,dc5a8f1d8,...,3ecc09859,9281abeea,8675bec0b,3a13ed79a,f677d4d13,71b203550,137efaa80,fb36b89d9,7e293fbaf,9fc776466
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.603968,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.508658,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# Scale values. Since it's time-series we shouldn't scale column-wise
mean = np.mean(train_df.values)
std = np.std(train_df.values)

train_df.loc[:, :] = ((train_df.values - mean) / std)
test_df.loc[:, :] = ((test_df.values - mean) / std)

train_df.head()

,48df886f9,0deb4b6a8,34b15f335,a8cb14b00,2f0771a37,30347e683,d08d1fbe3,6ee66e115,20aa07010,dc5a8f1d8,...,3ecc09859,9281abeea,8675bec0b,3a13ed79a,f677d4d13,71b203550,137efaa80,fb36b89d9,7e293fbaf,9fc776466
0,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,...,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255
1,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,5.601782,-0.178255,...,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255
2,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,...,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255
3,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,...,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255
4,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,5.564059,-0.178255,...,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255,-0.178255

In [8]:
# https://www.kaggle.com/johnfarrell/giba-s-property-extended-extended-result
ordered_cols = [
    'f190486d6', '58e2e02e6', 'eeb9cd3aa', '9fd594eec', '6eef030c1', '15ace8c9f', 
    'fb0f5dbfe', '58e056e12', '20aa07010', '024c577b9', 'd6bb78916', 'b43a7cfd5', 
    '58232a6fb', '1702b5bf0', '324921c7b', '62e59a501', '2ec5b290f', '241f0f867', 
    'fb49e4212', '66ace2992', 'f74e8f13d', '5c6487af1', '963a49cdc', '26fc93eb7', 
    '1931ccfdd', '703885424', '70feb1494', '491b9ee45', '23310aa6f', 'e176a204a', 
    '6619d81fc', '1db387535', 'fc99f9426', '91f701ba2', '0572565c2', '190db8488', 
    'adb64ff71', 'c47340d97', 'c5a231d81', '0ff32eb98'
][::-1]

# LSTM with Keras

In [9]:
from sklearn.model_selection import train_test_split
from keras.callbacks import *
from keras.layers import *
from keras.optimizers import *
from keras.callbacks import *
from keras.models import Model, Sequential

val_fraction = 0.2

# Split into train & test
X_train, X_val, y_train, y_val = train_test_split(
    train_df[ordered_cols],
    y.values, 
    test_size=val_fraction,
    random_state=42,
    shuffle=True
)

# Loss function
def rmse(y_true, y_pred):
    return K.sqrt(K.mean(K.square(y_pred - y_true), axis=-1))

Using TensorFlow backend.

In [10]:
from keras.regularizers import L1L2

reg_none = L1L2(l1=0.0, l2=0.0)
reg_L1 = L1L2(l1=0.01, l2=0.0)
reg_L2 = L1L2(l1=0.0, l2=0.01)
reg_L1L2 = L1L2(l1=0.01, l2=0.01)

def build_LSTM_model(reg, unit=64):
    model = Sequential()
    model.add(LSTM(unit, return_sequences=True, input_shape=(len(ordered_cols), 1)))
    model.add(LSTM(unit, return_sequences=True, kernel_regularizer=reg))
    model.add(LSTM(int(unit/2)))
    model.add(Dense(1, activation='linear'))
    return model

### LSTM Models

In [11]:
# baseline
# model = build_LSTM_model(reg_none)
# model.compile(loss=rmse, optimizer='adam')

# model.fit(
#     np.expand_dims(X_train, 2), y_train,
#     epochs=20,
#     validation_data=(np.expand_dims(X_val, 2), y_val),
#     callbacks=[
#         ReduceLROnPlateau(patience=2, verbose=1),
#         EarlyStopping(patience=3, min_delta=1e-5)
#     ]
# )

In [12]:
# L1 regularized
# model_L1 = build_LSTM_model(reg_L1)
# model_L1.compile(loss=rmse, optimizer='adam')

# model_L1.fit(
#     np.expand_dims(X_train, 2), y_train,
#     epochs=20,
#     validation_data=(np.expand_dims(X_val, 2), y_val),
#     callbacks=[
#         ReduceLROnPlateau(patience=2, verbose=1),
#         EarlyStopping(patience=3, min_delta=1e-5)
#     ]
# )

In [13]:
# L2 regularized
# model_L2 = build_LSTM_model(reg_L2)
# model_L2.compile(loss=rmse, optimizer='adam')

# model_L2.fit(
#     np.expand_dims(X_train, 2), y_train,
#     epochs=20,
#     validation_data=(np.expand_dims(X_val, 2), y_val),
#     callbacks=[
#         ReduceLROnPlateau(patience=2, verbose=1),
#         EarlyStopping(patience=3, min_delta=1e-5)
#     ]
# )

In [14]:
# L1 + L2 regulrized
# model_L1L2 = build_LSTM_model(reg_L1L2)

# model_L1L2.compile(loss=rmse, optimizer='adam')

# model_L1L2.fit(
#     np.expand_dims(X_train, 2), y_train,
#     epochs=20,
#     validation_data=(np.expand_dims(X_val, 2), y_val),
#     callbacks=[
#         ReduceLROnPlateau(patience=2, verbose=1),
#         EarlyStopping(patience=3, min_delta=1e-5)
#     ]
# )

# Save Models

In [15]:
# model.save('model.h5')
# model_L1.save('model_L1.h5')
# model_L2.save('model_L2.h5')
# model_L1L2.save('model_L1L2.h5')

# Load Models

In [17]:
from keras.models import load_model
model = load_model('model.h5', custom_objects={'rmse': rmse})
model_L1 = load_model('model_L1.h5', custom_objects={'rmse': rmse})
model_L2 = load_model('model_L2.h5', custom_objects={'rmse': rmse})
model_L1L2 = load_model('model_L1L2.h5', custom_objects={'rmse': rmse})

In [18]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_37 (LSTM)               (None, 40, 64)            16896
_________________________________________________________________
lstm_38 (LSTM)               (None, 40, 64)            33024
_________________________________________________________________
lstm_39 (LSTM)               (None, 32)                12416
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 33
=================================================================
Total params: 62,369
Trainable params: 62,369
Non-trainable params: 0
_________________________________________________________________

# Ensemble and Predict

In [ ]:
test_df.head()

model_to_ensemble = [model, model_L1, model_L2, model_L1L2]

ensemble = None

for m in model_to_ensemble:
    pred = np.expm1(model.predict(np.expand_dims(test_df[ordered_cols].values, 2)))
    
    if ensemble is None:
        ensemble = pred
    else:
        ensemble = ensemble + pred

ensemble = ensemble / len(model_to_ensemble)

sub = pd.DataFrame()
sub['ID'] = test_ID
sub['target'] = ensemble
sub.to_csv('submission_lstm.csv',index=False)